// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function CanRedo():Promise<boolean>;

export function CanUndo():Promise<boolean>;

export function ClearAllFilters():Promise<void>;

export function FilterComponents(arg1:Array<entities.ComponentFilterDTO>):Promise<void>;

export function GetComponentByPath(arg1:string):Promise<entities.ComponentDTO>;

export function GetDeclaredComponents():Promise<Array<entities.DeclaredComponent>>;

export function GetInitialFilters():Promise<entities.InitialFilters>;

export function Redo():Promise<void>;

export function Undo():Promise<void>;
