// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CanRedo() {
  return window['go']['service']['ComponentServiceImpl']['CanRedo']();
}

export function CanUndo() {
  return window['go']['service']['ComponentServiceImpl']['CanUndo']();
}

export function ClearAllFilters() {
  return window['go']['service']['ComponentServiceImpl']['ClearAllFilters']();
}

export function FilterComponents(arg1) {
  return window['go']['service']['ComponentServiceImpl']['FilterComponents'](arg1);
}

export function GetComponentByPath(arg1) {
  return window['go']['service']['ComponentServiceImpl']['GetComponentByPath'](arg1);
}

export function GetDeclaredComponents() {
  return window['go']['service']['ComponentServiceImpl']['GetDeclaredComponents']();
}

export function GetInitialFilters() {
  return window['go']['service']['ComponentServiceImpl']['GetInitialFilters']();
}

export function Redo() {
  return window['go']['service']['ComponentServiceImpl']['Redo']();
}

export function SearchComponents(arg1) {
  return window['go']['service']['ComponentServiceImpl']['SearchComponents'](arg1);
}

export function Undo() {
  return window['go']['service']['ComponentServiceImpl']['Undo']();
}
