// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalFile(arg1) {
  return window['go']['service']['FileServiceImpl']['GetLocalFile'](arg1);
}

export function GetRemoteFile(arg1) {
  return window['go']['service']['FileServiceImpl']['GetRemoteFile'](arg1);
}
