// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function GetGroupedShortcuts():Promise<Record<entities.Group, Array<entities.Shortcut>>>;

export function GetShortcuts():Promise<Array<entities.Shortcut>>;
