// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGroupedShortcuts() {
  return window['go']['service']['KeyboardServiceInMemoryImpl']['GetGroupedShortcuts']();
}

export function GetShortcuts() {
  return window['go']['service']['KeyboardServiceInMemoryImpl']['GetShortcuts']();
}
