// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAll() {
  return window['go']['service']['LicenseServiceImpl']['GetAll']();
}

export function GetLicensesByPurl(arg1) {
  return window['go']['service']['LicenseServiceImpl']['GetLicensesByPurl'](arg1);
}
