// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function GetAll():Promise<Array<entities.License>>;

export function GetLicensesByPurl(arg1:entities.ComponentRequest):Promise<entities.GetLicensesByPurlResponse>;
