// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAll(arg1) {
  return window['go']['service']['ResultServiceImpl']['GetAll'](arg1);
}

export function GetByPath(arg1) {
  return window['go']['service']['ResultServiceImpl']['GetByPath'](arg1);
}

export function SetContext(arg1) {
  return window['go']['service']['ResultServiceImpl']['SetContext'](arg1);
}
