// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function GetAll(arg1:entities.RequestResultDTO):Promise<Array<entities.ResultDTO>>;
