// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortScan() {
  return window['go']['service']['ScanServicePythonImpl']['AbortScan']();
}

export function CheckDependencies() {
  return window['go']['service']['ScanServicePythonImpl']['CheckDependencies']();
}

export function GetDefaultScanArgs() {
  return window['go']['service']['ScanServicePythonImpl']['GetDefaultScanArgs']();
}

export function GetScanArgs() {
  return window['go']['service']['ScanServicePythonImpl']['GetScanArgs']();
}

export function GetSensitiveDefaultScanArgs() {
  return window['go']['service']['ScanServicePythonImpl']['GetSensitiveDefaultScanArgs']();
}

export function Scan(arg1) {
  return window['go']['service']['ScanServicePythonImpl']['Scan'](arg1);
}

export function ScanStream(arg1) {
  return window['go']['service']['ScanServicePythonImpl']['ScanStream'](arg1);
}

export function SetContext(arg1) {
  return window['go']['service']['ScanServicePythonImpl']['SetContext'](arg1);
}
