// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CheckDependencies():Promise<void>;

export function GetDefaultScanArgs():Promise<Array<string>>;

export function Scan(arg1:Array<string>):Promise<void>;

export function ScanStream(arg1:Array<string>):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
