// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function AddStagedScanningSkipPattern(arg1:string):Promise<void>;

export function CommitStagedSkipPatterns():Promise<void>;

export function DiscardStagedSkipPatterns():Promise<void>;

export function GetSettings():Promise<entities.SettingsFile>;

export function HasStagedChanges():Promise<boolean>;

export function HasUnsavedChanges():Promise<boolean>;

export function RemoveStagedScanningSkipPattern(arg1:string):Promise<void>;

export function Save():Promise<void>;
