// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['service']['ScanossSettingsServiceImp']['GetSettings']();
}

export function HasUnsavedChanges() {
  return window['go']['service']['ScanossSettingsServiceImp']['HasUnsavedChanges']();
}

export function Save() {
  return window['go']['service']['ScanossSettingsServiceImp']['Save']();
}
