// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function AddScanningSkipPattern(arg1:string):Promise<void>;

export function GetSettings():Promise<entities.SettingsFile>;

export function HasUnsavedChanges():Promise<boolean>;

export function RemoveScanningSkipPattern(arg1:string):Promise<void>;

export function Save():Promise<void>;
