// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Scan(arg1) {
  return window['go']['service']['ScanServicePythonImpl']['Scan'](arg1);
}
