// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStagedScanningSkipPattern(arg1) {
  return window['go']['service']['ScanossSettingsServiceImp']['AddStagedScanningSkipPattern'](arg1);
}

export function CommitStagedScanningSkipPatterns() {
  return window['go']['service']['ScanossSettingsServiceImp']['CommitStagedScanningSkipPatterns']();
}

export function DiscardStagedScanningSkipPatterns() {
  return window['go']['service']['ScanossSettingsServiceImp']['DiscardStagedScanningSkipPatterns']();
}

export function GetSettings() {
  return window['go']['service']['ScanossSettingsServiceImp']['GetSettings']();
}

export function HasStagedScanningSkipPatternChanges() {
  return window['go']['service']['ScanossSettingsServiceImp']['HasStagedScanningSkipPatternChanges']();
}

export function HasUnsavedChanges() {
  return window['go']['service']['ScanossSettingsServiceImp']['HasUnsavedChanges']();
}

export function RemoveStagedScanningSkipPattern(arg1, arg2) {
  return window['go']['service']['ScanossSettingsServiceImp']['RemoveStagedScanningSkipPattern'](arg1, arg2);
}

export function Save() {
  return window['go']['service']['ScanossSettingsServiceImp']['Save']();
}
