// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function GetChildren(arg1:string,arg2:number,arg3:number):Promise<entities.TreeNodeResponse>;

export function GetNode(arg1:string):Promise<entities.TreeNode>;

export function GetRootNodes(arg1:number,arg2:number):Promise<entities.TreeNodeResponse>;

export function SearchNodes(arg1:string,arg2:number,arg3:number):Promise<entities.TreeNodeResponse>;
