// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChildren(arg1, arg2, arg3) {
  return window['go']['service']['TreeServiceImpl']['GetChildren'](arg1, arg2, arg3);
}

export function GetNode(arg1) {
  return window['go']['service']['TreeServiceImpl']['GetNode'](arg1);
}

export function GetRootNodes(arg1, arg2) {
  return window['go']['service']['TreeServiceImpl']['GetRootNodes'](arg1, arg2);
}

export function SearchNodes(arg1, arg2, arg3) {
  return window['go']['service']['TreeServiceImpl']['SearchNodes'](arg1, arg2, arg3);
}
