// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';
import {context} from '../models';

export function ApplyUpdate(arg1:string):Promise<void>;

export function CheckForFailedUpdate():Promise<void>;

export function CheckForUpdate():Promise<entities.UpdateInfo>;

export function DownloadUpdate(arg1:entities.UpdateInfo):Promise<string>;

export function GetCurrentVersion():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function VerifyUpdateSuccess():Promise<void>;
