// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['service']['UpdateServiceImpl']['ApplyUpdate'](arg1);
}

export function CheckForUpdate() {
  return window['go']['service']['UpdateServiceImpl']['CheckForUpdate']();
}

export function DownloadUpdate(arg1) {
  return window['go']['service']['UpdateServiceImpl']['DownloadUpdate'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['service']['UpdateServiceImpl']['GetCurrentVersion']();
}

export function SetContext(arg1) {
  return window['go']['service']['UpdateServiceImpl']['SetContext'](arg1);
}
