// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/scanoss/scanoss.cc/backend/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdateService is an autogenerated mock type for the UpdateService type
type MockUpdateService struct {
	mock.Mock
}

type MockUpdateService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateService) EXPECT() *MockUpdateService_Expecter {
	return &MockUpdateService_Expecter{mock: &_m.Mock}
}

// ApplyUpdate provides a mock function with given fields: updatePath
func (_m *MockUpdateService) ApplyUpdate(updatePath string) error {
	ret := _m.Called(updatePath)

	if len(ret) == 0 {
		panic("no return value specified for ApplyUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(updatePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdateService_ApplyUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyUpdate'
type MockUpdateService_ApplyUpdate_Call struct {
	*mock.Call
}

// ApplyUpdate is a helper method to define mock.On call
//   - updatePath string
func (_e *MockUpdateService_Expecter) ApplyUpdate(updatePath interface{}) *MockUpdateService_ApplyUpdate_Call {
	return &MockUpdateService_ApplyUpdate_Call{Call: _e.mock.On("ApplyUpdate", updatePath)}
}

func (_c *MockUpdateService_ApplyUpdate_Call) Run(run func(updatePath string)) *MockUpdateService_ApplyUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUpdateService_ApplyUpdate_Call) Return(_a0 error) *MockUpdateService_ApplyUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateService_ApplyUpdate_Call) RunAndReturn(run func(string) error) *MockUpdateService_ApplyUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// CheckForUpdate provides a mock function with given fields:
func (_m *MockUpdateService) CheckForUpdate() (*entities.UpdateInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckForUpdate")
	}

	var r0 *entities.UpdateInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() (*entities.UpdateInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *entities.UpdateInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UpdateInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateService_CheckForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckForUpdate'
type MockUpdateService_CheckForUpdate_Call struct {
	*mock.Call
}

// CheckForUpdate is a helper method to define mock.On call
func (_e *MockUpdateService_Expecter) CheckForUpdate() *MockUpdateService_CheckForUpdate_Call {
	return &MockUpdateService_CheckForUpdate_Call{Call: _e.mock.On("CheckForUpdate")}
}

func (_c *MockUpdateService_CheckForUpdate_Call) Run(run func()) *MockUpdateService_CheckForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdateService_CheckForUpdate_Call) Return(_a0 *entities.UpdateInfo, _a1 error) *MockUpdateService_CheckForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateService_CheckForUpdate_Call) RunAndReturn(run func() (*entities.UpdateInfo, error)) *MockUpdateService_CheckForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadUpdate provides a mock function with given fields: updateInfo
func (_m *MockUpdateService) DownloadUpdate(updateInfo *entities.UpdateInfo) (string, error) {
	ret := _m.Called(updateInfo)

	if len(ret) == 0 {
		panic("no return value specified for DownloadUpdate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.UpdateInfo) (string, error)); ok {
		return rf(updateInfo)
	}
	if rf, ok := ret.Get(0).(func(*entities.UpdateInfo) string); ok {
		r0 = rf(updateInfo)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*entities.UpdateInfo) error); ok {
		r1 = rf(updateInfo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateService_DownloadUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadUpdate'
type MockUpdateService_DownloadUpdate_Call struct {
	*mock.Call
}

// DownloadUpdate is a helper method to define mock.On call
//   - updateInfo *entities.UpdateInfo
func (_e *MockUpdateService_Expecter) DownloadUpdate(updateInfo interface{}) *MockUpdateService_DownloadUpdate_Call {
	return &MockUpdateService_DownloadUpdate_Call{Call: _e.mock.On("DownloadUpdate", updateInfo)}
}

func (_c *MockUpdateService_DownloadUpdate_Call) Run(run func(updateInfo *entities.UpdateInfo)) *MockUpdateService_DownloadUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.UpdateInfo))
	})
	return _c
}

func (_c *MockUpdateService_DownloadUpdate_Call) Return(_a0 string, _a1 error) *MockUpdateService_DownloadUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateService_DownloadUpdate_Call) RunAndReturn(run func(*entities.UpdateInfo) (string, error)) *MockUpdateService_DownloadUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentVersion provides a mock function with given fields:
func (_m *MockUpdateService) GetCurrentVersion() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentVersion")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockUpdateService_GetCurrentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentVersion'
type MockUpdateService_GetCurrentVersion_Call struct {
	*mock.Call
}

// GetCurrentVersion is a helper method to define mock.On call
func (_e *MockUpdateService_Expecter) GetCurrentVersion() *MockUpdateService_GetCurrentVersion_Call {
	return &MockUpdateService_GetCurrentVersion_Call{Call: _e.mock.On("GetCurrentVersion")}
}

func (_c *MockUpdateService_GetCurrentVersion_Call) Run(run func()) *MockUpdateService_GetCurrentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdateService_GetCurrentVersion_Call) Return(_a0 string) *MockUpdateService_GetCurrentVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdateService_GetCurrentVersion_Call) RunAndReturn(run func() string) *MockUpdateService_GetCurrentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// SetContext provides a mock function with given fields: ctx
func (_m *MockUpdateService) SetContext(ctx context.Context) {
	_m.Called(ctx)
}

// MockUpdateService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockUpdateService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUpdateService_Expecter) SetContext(ctx interface{}) *MockUpdateService_SetContext_Call {
	return &MockUpdateService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockUpdateService_SetContext_Call) Run(run func(ctx context.Context)) *MockUpdateService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUpdateService_SetContext_Call) Return() *MockUpdateService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUpdateService_SetContext_Call) RunAndReturn(run func(context.Context)) *MockUpdateService_SetContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateService creates a new instance of MockUpdateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateService {
	mock := &MockUpdateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
