// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/scanoss/scanoss.cc/backend/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockScanossApiService is an autogenerated mock type for the ScanossApiService type
type MockScanossApiService struct {
	mock.Mock
}

type MockScanossApiService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScanossApiService) EXPECT() *MockScanossApiService_Expecter {
	return &MockScanossApiService_Expecter{mock: &_m.Mock}
}

// GetLicensesByPurl provides a mock function with given fields: request
func (_m *MockScanossApiService) GetLicensesByPurl(request entities.ComponentRequest) (entities.GetLicensesByPurlResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for GetLicensesByPurl")
	}

	var r0 entities.GetLicensesByPurlResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.ComponentRequest) (entities.GetLicensesByPurlResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(entities.ComponentRequest) entities.GetLicensesByPurlResponse); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(entities.GetLicensesByPurlResponse)
	}

	if rf, ok := ret.Get(1).(func(entities.ComponentRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScanossApiService_GetLicensesByPurl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLicensesByPurl'
type MockScanossApiService_GetLicensesByPurl_Call struct {
	*mock.Call
}

// GetLicensesByPurl is a helper method to define mock.On call
//   - request entities.ComponentRequest
func (_e *MockScanossApiService_Expecter) GetLicensesByPurl(request interface{}) *MockScanossApiService_GetLicensesByPurl_Call {
	return &MockScanossApiService_GetLicensesByPurl_Call{Call: _e.mock.On("GetLicensesByPurl", request)}
}

func (_c *MockScanossApiService_GetLicensesByPurl_Call) Run(run func(request entities.ComponentRequest)) *MockScanossApiService_GetLicensesByPurl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.ComponentRequest))
	})
	return _c
}

func (_c *MockScanossApiService_GetLicensesByPurl_Call) Return(_a0 entities.GetLicensesByPurlResponse, _a1 error) *MockScanossApiService_GetLicensesByPurl_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScanossApiService_GetLicensesByPurl_Call) RunAndReturn(run func(entities.ComponentRequest) (entities.GetLicensesByPurlResponse, error)) *MockScanossApiService_GetLicensesByPurl_Call {
	_c.Call.Return(run)
	return _c
}

// SearchComponents provides a mock function with given fields: request
func (_m *MockScanossApiService) SearchComponents(request entities.ComponentSearchRequest) (entities.ComponentSearchResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for SearchComponents")
	}

	var r0 entities.ComponentSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.ComponentSearchRequest) (entities.ComponentSearchResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(entities.ComponentSearchRequest) entities.ComponentSearchResponse); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(entities.ComponentSearchResponse)
	}

	if rf, ok := ret.Get(1).(func(entities.ComponentSearchRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScanossApiService_SearchComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchComponents'
type MockScanossApiService_SearchComponents_Call struct {
	*mock.Call
}

// SearchComponents is a helper method to define mock.On call
//   - request entities.ComponentSearchRequest
func (_e *MockScanossApiService_Expecter) SearchComponents(request interface{}) *MockScanossApiService_SearchComponents_Call {
	return &MockScanossApiService_SearchComponents_Call{Call: _e.mock.On("SearchComponents", request)}
}

func (_c *MockScanossApiService_SearchComponents_Call) Run(run func(request entities.ComponentSearchRequest)) *MockScanossApiService_SearchComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.ComponentSearchRequest))
	})
	return _c
}

func (_c *MockScanossApiService_SearchComponents_Call) Return(_a0 entities.ComponentSearchResponse, _a1 error) *MockScanossApiService_SearchComponents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScanossApiService_SearchComponents_Call) RunAndReturn(run func(entities.ComponentSearchRequest) (entities.ComponentSearchResponse, error)) *MockScanossApiService_SearchComponents_Call {
	_c.Call.Return(run)
	return _c
}

// SetContext provides a mock function with given fields: ctx
func (_m *MockScanossApiService) SetContext(ctx context.Context) {
	_m.Called(ctx)
}

// MockScanossApiService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockScanossApiService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockScanossApiService_Expecter) SetContext(ctx interface{}) *MockScanossApiService_SetContext_Call {
	return &MockScanossApiService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockScanossApiService_SetContext_Call) Run(run func(ctx context.Context)) *MockScanossApiService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockScanossApiService_SetContext_Call) Return() *MockScanossApiService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockScanossApiService_SetContext_Call) RunAndReturn(run func(context.Context)) *MockScanossApiService_SetContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScanossApiService creates a new instance of MockScanossApiService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScanossApiService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScanossApiService {
	mock := &MockScanossApiService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
