// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	entities "github.com/scanoss/scanoss.lui/backend/main/pkg/component/entities"
	mock "github.com/stretchr/testify/mock"

	scanoss_settingsentities "github.com/scanoss/scanoss.lui/backend/main/pkg/common/scanoss_settings/entities"
)

// MockComponentService is an autogenerated mock type for the ComponentService type
type MockComponentService struct {
	mock.Mock
}

type MockComponentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponentService) EXPECT() *MockComponentService_Expecter {
	return &MockComponentService_Expecter{mock: &_m.Mock}
}

// ClearAllFilters provides a mock function with given fields:
func (_m *MockComponentService) ClearAllFilters() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClearAllFilters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponentService_ClearAllFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAllFilters'
type MockComponentService_ClearAllFilters_Call struct {
	*mock.Call
}

// ClearAllFilters is a helper method to define mock.On call
func (_e *MockComponentService_Expecter) ClearAllFilters() *MockComponentService_ClearAllFilters_Call {
	return &MockComponentService_ClearAllFilters_Call{Call: _e.mock.On("ClearAllFilters")}
}

func (_c *MockComponentService_ClearAllFilters_Call) Run(run func()) *MockComponentService_ClearAllFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentService_ClearAllFilters_Call) Return(_a0 error) *MockComponentService_ClearAllFilters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentService_ClearAllFilters_Call) RunAndReturn(run func() error) *MockComponentService_ClearAllFilters_Call {
	_c.Call.Return(run)
	return _c
}

// FilterComponents provides a mock function with given fields: dto
func (_m *MockComponentService) FilterComponents(dto []entities.ComponentFilterDTO) error {
	ret := _m.Called(dto)

	if len(ret) == 0 {
		panic("no return value specified for FilterComponents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]entities.ComponentFilterDTO) error); ok {
		r0 = rf(dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponentService_FilterComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterComponents'
type MockComponentService_FilterComponents_Call struct {
	*mock.Call
}

// FilterComponents is a helper method to define mock.On call
//   - dto []entities.ComponentFilterDTO
func (_e *MockComponentService_Expecter) FilterComponents(dto interface{}) *MockComponentService_FilterComponents_Call {
	return &MockComponentService_FilterComponents_Call{Call: _e.mock.On("FilterComponents", dto)}
}

func (_c *MockComponentService_FilterComponents_Call) Run(run func(dto []entities.ComponentFilterDTO)) *MockComponentService_FilterComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]entities.ComponentFilterDTO))
	})
	return _c
}

func (_c *MockComponentService_FilterComponents_Call) Return(_a0 error) *MockComponentService_FilterComponents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentService_FilterComponents_Call) RunAndReturn(run func([]entities.ComponentFilterDTO) error) *MockComponentService_FilterComponents_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponentByFilePath provides a mock function with given fields: filePath
func (_m *MockComponentService) GetComponentByFilePath(filePath string) (entities.Component, error) {
	ret := _m.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for GetComponentByFilePath")
	}

	var r0 entities.Component
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.Component, error)); ok {
		return rf(filePath)
	}
	if rf, ok := ret.Get(0).(func(string) entities.Component); ok {
		r0 = rf(filePath)
	} else {
		r0 = ret.Get(0).(entities.Component)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComponentService_GetComponentByFilePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentByFilePath'
type MockComponentService_GetComponentByFilePath_Call struct {
	*mock.Call
}

// GetComponentByFilePath is a helper method to define mock.On call
//   - filePath string
func (_e *MockComponentService_Expecter) GetComponentByFilePath(filePath interface{}) *MockComponentService_GetComponentByFilePath_Call {
	return &MockComponentService_GetComponentByFilePath_Call{Call: _e.mock.On("GetComponentByFilePath", filePath)}
}

func (_c *MockComponentService_GetComponentByFilePath_Call) Run(run func(filePath string)) *MockComponentService_GetComponentByFilePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockComponentService_GetComponentByFilePath_Call) Return(_a0 entities.Component, _a1 error) *MockComponentService_GetComponentByFilePath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComponentService_GetComponentByFilePath_Call) RunAndReturn(run func(string) (entities.Component, error)) *MockComponentService_GetComponentByFilePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeclaredComponents provides a mock function with given fields:
func (_m *MockComponentService) GetDeclaredComponents() ([]entities.DeclaredComponent, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDeclaredComponents")
	}

	var r0 []entities.DeclaredComponent
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.DeclaredComponent, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.DeclaredComponent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.DeclaredComponent)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComponentService_GetDeclaredComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeclaredComponents'
type MockComponentService_GetDeclaredComponents_Call struct {
	*mock.Call
}

// GetDeclaredComponents is a helper method to define mock.On call
func (_e *MockComponentService_Expecter) GetDeclaredComponents() *MockComponentService_GetDeclaredComponents_Call {
	return &MockComponentService_GetDeclaredComponents_Call{Call: _e.mock.On("GetDeclaredComponents")}
}

func (_c *MockComponentService_GetDeclaredComponents_Call) Run(run func()) *MockComponentService_GetDeclaredComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentService_GetDeclaredComponents_Call) Return(_a0 []entities.DeclaredComponent, _a1 error) *MockComponentService_GetDeclaredComponents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComponentService_GetDeclaredComponents_Call) RunAndReturn(run func() ([]entities.DeclaredComponent, error)) *MockComponentService_GetDeclaredComponents_Call {
	_c.Call.Return(run)
	return _c
}

// GetInitialFilters provides a mock function with given fields:
func (_m *MockComponentService) GetInitialFilters() ([]scanoss_settingsentities.ComponentFilter, []scanoss_settingsentities.ComponentFilter) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInitialFilters")
	}

	var r0 []scanoss_settingsentities.ComponentFilter
	var r1 []scanoss_settingsentities.ComponentFilter
	if rf, ok := ret.Get(0).(func() ([]scanoss_settingsentities.ComponentFilter, []scanoss_settingsentities.ComponentFilter)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []scanoss_settingsentities.ComponentFilter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scanoss_settingsentities.ComponentFilter)
		}
	}

	if rf, ok := ret.Get(1).(func() []scanoss_settingsentities.ComponentFilter); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]scanoss_settingsentities.ComponentFilter)
		}
	}

	return r0, r1
}

// MockComponentService_GetInitialFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInitialFilters'
type MockComponentService_GetInitialFilters_Call struct {
	*mock.Call
}

// GetInitialFilters is a helper method to define mock.On call
func (_e *MockComponentService_Expecter) GetInitialFilters() *MockComponentService_GetInitialFilters_Call {
	return &MockComponentService_GetInitialFilters_Call{Call: _e.mock.On("GetInitialFilters")}
}

func (_c *MockComponentService_GetInitialFilters_Call) Run(run func()) *MockComponentService_GetInitialFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentService_GetInitialFilters_Call) Return(_a0 []scanoss_settingsentities.ComponentFilter, _a1 []scanoss_settingsentities.ComponentFilter) *MockComponentService_GetInitialFilters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComponentService_GetInitialFilters_Call) RunAndReturn(run func() ([]scanoss_settingsentities.ComponentFilter, []scanoss_settingsentities.ComponentFilter)) *MockComponentService_GetInitialFilters_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComponentService creates a new instance of MockComponentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponentService {
	mock := &MockComponentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
