// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockLicense is an autogenerated mock type for the License type
type MockLicense struct {
	mock.Mock
}

type MockLicense_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLicense) EXPECT() *MockLicense_Expecter {
	return &MockLicense_Expecter{mock: &_m.Mock}
}

// NewMockLicense creates a new instance of MockLicense. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLicense(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLicense {
	mock := &MockLicense{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
