// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	entities "github.com/scanoss/scanoss.lui/backend/main/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockResultMapper is an autogenerated mock type for the ResultMapper type
type MockResultMapper struct {
	mock.Mock
}

type MockResultMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResultMapper) EXPECT() *MockResultMapper_Expecter {
	return &MockResultMapper_Expecter{mock: &_m.Mock}
}

// MapToResultDTO provides a mock function with given fields: result
func (_m *MockResultMapper) MapToResultDTO(result entities.Result) entities.ResultDTO {
	ret := _m.Called(result)

	if len(ret) == 0 {
		panic("no return value specified for MapToResultDTO")
	}

	var r0 entities.ResultDTO
	if rf, ok := ret.Get(0).(func(entities.Result) entities.ResultDTO); ok {
		r0 = rf(result)
	} else {
		r0 = ret.Get(0).(entities.ResultDTO)
	}

	return r0
}

// MockResultMapper_MapToResultDTO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapToResultDTO'
type MockResultMapper_MapToResultDTO_Call struct {
	*mock.Call
}

// MapToResultDTO is a helper method to define mock.On call
//   - result entities.Result
func (_e *MockResultMapper_Expecter) MapToResultDTO(result interface{}) *MockResultMapper_MapToResultDTO_Call {
	return &MockResultMapper_MapToResultDTO_Call{Call: _e.mock.On("MapToResultDTO", result)}
}

func (_c *MockResultMapper_MapToResultDTO_Call) Run(run func(result entities.Result)) *MockResultMapper_MapToResultDTO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.Result))
	})
	return _c
}

func (_c *MockResultMapper_MapToResultDTO_Call) Return(_a0 entities.ResultDTO) *MockResultMapper_MapToResultDTO_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResultMapper_MapToResultDTO_Call) RunAndReturn(run func(entities.Result) entities.ResultDTO) *MockResultMapper_MapToResultDTO_Call {
	_c.Call.Return(run)
	return _c
}

// MapToResultDTOList provides a mock function with given fields: results
func (_m *MockResultMapper) MapToResultDTOList(results []entities.Result) []entities.ResultDTO {
	ret := _m.Called(results)

	if len(ret) == 0 {
		panic("no return value specified for MapToResultDTOList")
	}

	var r0 []entities.ResultDTO
	if rf, ok := ret.Get(0).(func([]entities.Result) []entities.ResultDTO); ok {
		r0 = rf(results)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.ResultDTO)
		}
	}

	return r0
}

// MockResultMapper_MapToResultDTOList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapToResultDTOList'
type MockResultMapper_MapToResultDTOList_Call struct {
	*mock.Call
}

// MapToResultDTOList is a helper method to define mock.On call
//   - results []entities.Result
func (_e *MockResultMapper_Expecter) MapToResultDTOList(results interface{}) *MockResultMapper_MapToResultDTOList_Call {
	return &MockResultMapper_MapToResultDTOList_Call{Call: _e.mock.On("MapToResultDTOList", results)}
}

func (_c *MockResultMapper_MapToResultDTOList_Call) Run(run func(results []entities.Result)) *MockResultMapper_MapToResultDTOList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]entities.Result))
	})
	return _c
}

func (_c *MockResultMapper_MapToResultDTOList_Call) Return(_a0 []entities.ResultDTO) *MockResultMapper_MapToResultDTOList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResultMapper_MapToResultDTOList_Call) RunAndReturn(run func([]entities.Result) []entities.ResultDTO) *MockResultMapper_MapToResultDTOList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResultMapper creates a new instance of MockResultMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResultMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResultMapper {
	mock := &MockResultMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
