// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	entities "github.com/scanoss/scanoss.lui/backend/main/pkg/component/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockComponentController is an autogenerated mock type for the ComponentController type
type MockComponentController struct {
	mock.Mock
}

type MockComponentController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponentController) EXPECT() *MockComponentController_Expecter {
	return &MockComponentController_Expecter{mock: &_m.Mock}
}

// CanRedo provides a mock function with given fields:
func (_m *MockComponentController) CanRedo() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanRedo")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockComponentController_CanRedo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanRedo'
type MockComponentController_CanRedo_Call struct {
	*mock.Call
}

// CanRedo is a helper method to define mock.On call
func (_e *MockComponentController_Expecter) CanRedo() *MockComponentController_CanRedo_Call {
	return &MockComponentController_CanRedo_Call{Call: _e.mock.On("CanRedo")}
}

func (_c *MockComponentController_CanRedo_Call) Run(run func()) *MockComponentController_CanRedo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentController_CanRedo_Call) Return(_a0 bool) *MockComponentController_CanRedo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentController_CanRedo_Call) RunAndReturn(run func() bool) *MockComponentController_CanRedo_Call {
	_c.Call.Return(run)
	return _c
}

// CanUndo provides a mock function with given fields:
func (_m *MockComponentController) CanUndo() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanUndo")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockComponentController_CanUndo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanUndo'
type MockComponentController_CanUndo_Call struct {
	*mock.Call
}

// CanUndo is a helper method to define mock.On call
func (_e *MockComponentController_Expecter) CanUndo() *MockComponentController_CanUndo_Call {
	return &MockComponentController_CanUndo_Call{Call: _e.mock.On("CanUndo")}
}

func (_c *MockComponentController_CanUndo_Call) Run(run func()) *MockComponentController_CanUndo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentController_CanUndo_Call) Return(_a0 bool) *MockComponentController_CanUndo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentController_CanUndo_Call) RunAndReturn(run func() bool) *MockComponentController_CanUndo_Call {
	_c.Call.Return(run)
	return _c
}

// FilterComponents provides a mock function with given fields: dto
func (_m *MockComponentController) FilterComponents(dto []entities.ComponentFilterDTO) error {
	ret := _m.Called(dto)

	if len(ret) == 0 {
		panic("no return value specified for FilterComponents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]entities.ComponentFilterDTO) error); ok {
		r0 = rf(dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponentController_FilterComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterComponents'
type MockComponentController_FilterComponents_Call struct {
	*mock.Call
}

// FilterComponents is a helper method to define mock.On call
//   - dto []entities.ComponentFilterDTO
func (_e *MockComponentController_Expecter) FilterComponents(dto interface{}) *MockComponentController_FilterComponents_Call {
	return &MockComponentController_FilterComponents_Call{Call: _e.mock.On("FilterComponents", dto)}
}

func (_c *MockComponentController_FilterComponents_Call) Run(run func(dto []entities.ComponentFilterDTO)) *MockComponentController_FilterComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]entities.ComponentFilterDTO))
	})
	return _c
}

func (_c *MockComponentController_FilterComponents_Call) Return(_a0 error) *MockComponentController_FilterComponents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentController_FilterComponents_Call) RunAndReturn(run func([]entities.ComponentFilterDTO) error) *MockComponentController_FilterComponents_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponentByPath provides a mock function with given fields: filePath
func (_m *MockComponentController) GetComponentByPath(filePath string) (entities.ComponentDTO, error) {
	ret := _m.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for GetComponentByPath")
	}

	var r0 entities.ComponentDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.ComponentDTO, error)); ok {
		return rf(filePath)
	}
	if rf, ok := ret.Get(0).(func(string) entities.ComponentDTO); ok {
		r0 = rf(filePath)
	} else {
		r0 = ret.Get(0).(entities.ComponentDTO)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComponentController_GetComponentByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentByPath'
type MockComponentController_GetComponentByPath_Call struct {
	*mock.Call
}

// GetComponentByPath is a helper method to define mock.On call
//   - filePath string
func (_e *MockComponentController_Expecter) GetComponentByPath(filePath interface{}) *MockComponentController_GetComponentByPath_Call {
	return &MockComponentController_GetComponentByPath_Call{Call: _e.mock.On("GetComponentByPath", filePath)}
}

func (_c *MockComponentController_GetComponentByPath_Call) Run(run func(filePath string)) *MockComponentController_GetComponentByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockComponentController_GetComponentByPath_Call) Return(_a0 entities.ComponentDTO, _a1 error) *MockComponentController_GetComponentByPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComponentController_GetComponentByPath_Call) RunAndReturn(run func(string) (entities.ComponentDTO, error)) *MockComponentController_GetComponentByPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeclaredComponents provides a mock function with given fields:
func (_m *MockComponentController) GetDeclaredComponents() ([]entities.DeclaredComponent, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDeclaredComponents")
	}

	var r0 []entities.DeclaredComponent
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.DeclaredComponent, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.DeclaredComponent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.DeclaredComponent)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComponentController_GetDeclaredComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeclaredComponents'
type MockComponentController_GetDeclaredComponents_Call struct {
	*mock.Call
}

// GetDeclaredComponents is a helper method to define mock.On call
func (_e *MockComponentController_Expecter) GetDeclaredComponents() *MockComponentController_GetDeclaredComponents_Call {
	return &MockComponentController_GetDeclaredComponents_Call{Call: _e.mock.On("GetDeclaredComponents")}
}

func (_c *MockComponentController_GetDeclaredComponents_Call) Run(run func()) *MockComponentController_GetDeclaredComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentController_GetDeclaredComponents_Call) Return(_a0 []entities.DeclaredComponent, _a1 error) *MockComponentController_GetDeclaredComponents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComponentController_GetDeclaredComponents_Call) RunAndReturn(run func() ([]entities.DeclaredComponent, error)) *MockComponentController_GetDeclaredComponents_Call {
	_c.Call.Return(run)
	return _c
}

// Redo provides a mock function with given fields:
func (_m *MockComponentController) Redo() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Redo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponentController_Redo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redo'
type MockComponentController_Redo_Call struct {
	*mock.Call
}

// Redo is a helper method to define mock.On call
func (_e *MockComponentController_Expecter) Redo() *MockComponentController_Redo_Call {
	return &MockComponentController_Redo_Call{Call: _e.mock.On("Redo")}
}

func (_c *MockComponentController_Redo_Call) Run(run func()) *MockComponentController_Redo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentController_Redo_Call) Return(_a0 error) *MockComponentController_Redo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentController_Redo_Call) RunAndReturn(run func() error) *MockComponentController_Redo_Call {
	_c.Call.Return(run)
	return _c
}

// Undo provides a mock function with given fields:
func (_m *MockComponentController) Undo() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Undo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockComponentController_Undo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Undo'
type MockComponentController_Undo_Call struct {
	*mock.Call
}

// Undo is a helper method to define mock.On call
func (_e *MockComponentController_Expecter) Undo() *MockComponentController_Undo_Call {
	return &MockComponentController_Undo_Call{Call: _e.mock.On("Undo")}
}

func (_c *MockComponentController_Undo_Call) Run(run func()) *MockComponentController_Undo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComponentController_Undo_Call) Return(_a0 error) *MockComponentController_Undo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockComponentController_Undo_Call) RunAndReturn(run func() error) *MockComponentController_Undo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComponentController creates a new instance of MockComponentController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponentController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponentController {
	mock := &MockComponentController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
