// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ResultGetAll(arg1) {
  return window['go']['handler']['ResultHandler']['ResultGetAll'](arg1);
}
