// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function ResultGetAll(arg1:common.RequestResultDTO):Promise<Array<common.ResultDTO>>;
