// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function ComponentFilter(arg1:entities.ComponentFilterDTO):Promise<void>;

export function ComponentFilterCanRedo():Promise<boolean>;

export function ComponentFilterCanUndo():Promise<boolean>;

export function ComponentFilterRedo():Promise<void>;

export function ComponentFilterUndo():Promise<void>;

export function ComponentGet(arg1:string):Promise<entities.ComponentDTO>;
