// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ComponentFilter(arg1) {
  return window['go']['handlers']['ComponentHandler']['ComponentFilter'](arg1);
}

export function ComponentGet(arg1) {
  return window['go']['handlers']['ComponentHandler']['ComponentGet'](arg1);
}
