// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ComponentFilter(arg1) {
  return window['go']['handlers']['ComponentHandler']['ComponentFilter'](arg1);
}

export function ComponentFilterCanRedo() {
  return window['go']['handlers']['ComponentHandler']['ComponentFilterCanRedo']();
}

export function ComponentFilterCanUndo() {
  return window['go']['handlers']['ComponentHandler']['ComponentFilterCanUndo']();
}

export function ComponentFilterRedo() {
  return window['go']['handlers']['ComponentHandler']['ComponentFilterRedo']();
}

export function ComponentFilterUndo() {
  return window['go']['handlers']['ComponentHandler']['ComponentFilterUndo']();
}

export function ComponentGet(arg1) {
  return window['go']['handlers']['ComponentHandler']['ComponentGet'](arg1);
}
