// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileGetLocalContent(arg1) {
  return window['go']['handlers']['FileHandler']['FileGetLocalContent'](arg1);
}

export function FileGetRemoteContent(arg1) {
  return window['go']['handlers']['FileHandler']['FileGetRemoteContent'](arg1);
}
