// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function FileGetLocalContent(arg1:string):Promise<entities.FileDTO>;

export function FileGetRemoteContent(arg1:string):Promise<entities.FileDTO>;
