// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnShutDown(arg1) {
  return window['go']['handlers']['ScanossBomHandler']['OnShutDown'](arg1);
}

export function SaveScanossBomFile() {
  return window['go']['handlers']['ScanossBomHandler']['SaveScanossBomFile']();
}
