// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanoss_settings} from '../models';

export function GetScanossSettings():Promise<scanoss_settings.Module>;

export function HasUnsavedChanges():Promise<boolean>;

export function SaveScanossSettingsFile():Promise<void>;
