// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScanossSettings() {
  return window['go']['handlers']['ScanossSettingsHandler']['GetScanossSettings']();
}

export function HasUnsavedChanges() {
  return window['go']['handlers']['ScanossSettingsHandler']['HasUnsavedChanges']();
}

export function SaveScanossSettingsFile() {
  return window['go']['handlers']['ScanossSettingsHandler']['SaveScanossSettingsFile']();
}
