// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HasUnsavedChanges():Promise<boolean>;

export function SaveScanossBomFile():Promise<void>;
