/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/main'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const FilesFileIdLazyImport = createFileRoute('/files/$fileId')()

// Create/Update Routes

const MainRoute = MainImport.update({
  path: '/main',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const FilesFileIdLazyRoute = FilesFileIdLazyImport.update({
  path: '/files/$fileId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/files/$fileId.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/files/$fileId': {
      id: '/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/files/$fileId'
      preLoaderRoute: typeof FilesFileIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  MainRoute,
  FilesFileIdLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/main",
        "/files/$fileId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/main": {
      "filePath": "main.tsx"
    },
    "/files/$fileId": {
      "filePath": "files/$fileId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
