/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/_home'

// Create Virtual Routes

const HomeIndexLazyImport = createFileRoute('/_home/')()
const HomeFilesFilePathLazyImport = createFileRoute('/_home/files/$filePath')()

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexLazyRoute = HomeIndexLazyImport.update({
  path: '/',
  getParentRoute: () => HomeRoute,
} as any).lazy(() => import('./routes/_home/index.lazy').then((d) => d.Route))

const HomeFilesFilePathLazyRoute = HomeFilesFilePathLazyImport.update({
  path: '/files/$filePath',
  getParentRoute: () => HomeRoute,
} as any).lazy(() =>
  import('./routes/_home/files/$filePath.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexLazyImport
      parentRoute: typeof HomeImport
    }
    '/_home/files/$filePath': {
      id: '/_home/files/$filePath'
      path: '/files/$filePath'
      fullPath: '/files/$filePath'
      preLoaderRoute: typeof HomeFilesFilePathLazyImport
      parentRoute: typeof HomeImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  HomeRoute: HomeRoute.addChildren({
    HomeIndexLazyRoute,
    HomeFilesFilePathLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_home"
      ]
    },
    "/_home": {
      "filePath": "_home.tsx",
      "children": [
        "/_home/",
        "/_home/files/$filePath"
      ]
    },
    "/_home/": {
      "filePath": "_home/index.lazy.tsx",
      "parent": "/_home"
    },
    "/_home/files/$filePath": {
      "filePath": "_home/files/$filePath.lazy.tsx",
      "parent": "/_home"
    }
  }
}
ROUTE_MANIFEST_END */
