#!/bin/bash
APP_NAME="scanoss-lui"
APP_PATH="/Applications/$APP_NAME.app"
CLI_TARGET="$APP_PATH/Contents/MacOS/$APP_NAME"
LINK_PATH="/usr/local/bin/$APP_NAME"

if [ -f "$CLI_TARGET" ]; then
    [ -L "$LINK_PATH" ] && rm "$LINK_PATH"
    ln -s "$CLI_TARGET" "$LINK_PATH"
fi

exit 0
