// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockFileWatcher is an autogenerated mock type for the FileWatcher type
type MockFileWatcher struct {
	mock.Mock
}

type MockFileWatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileWatcher) EXPECT() *MockFileWatcher_Expecter {
	return &MockFileWatcher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *MockFileWatcher) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileWatcher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFileWatcher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFileWatcher_Expecter) Close() *MockFileWatcher_Close_Call {
	return &MockFileWatcher_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFileWatcher_Close_Call) Run(run func()) *MockFileWatcher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileWatcher_Close_Call) Return(_a0 error) *MockFileWatcher_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileWatcher_Close_Call) RunAndReturn(run func() error) *MockFileWatcher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields:
func (_m *MockFileWatcher) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileWatcher_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockFileWatcher_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockFileWatcher_Expecter) Start() *MockFileWatcher_Start_Call {
	return &MockFileWatcher_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockFileWatcher_Start_Call) Run(run func()) *MockFileWatcher_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileWatcher_Start_Call) Return(_a0 error) *MockFileWatcher_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileWatcher_Start_Call) RunAndReturn(run func() error) *MockFileWatcher_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileWatcher creates a new instance of MockFileWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileWatcher {
	mock := &MockFileWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
