// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockComponentLicense is an autogenerated mock type for the ComponentLicense type
type MockComponentLicense struct {
	mock.Mock
}

type MockComponentLicense_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponentLicense) EXPECT() *MockComponentLicense_Expecter {
	return &MockComponentLicense_Expecter{mock: &_m.Mock}
}

// NewMockComponentLicense creates a new instance of MockComponentLicense. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponentLicense(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponentLicense {
	mock := &MockComponentLicense{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
