// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keyboard} from '../models';

export function GetGroupedShortcuts():Promise<{[key: keyboard.Group]: Array<any>}>;

export function GetShortcuts():Promise<Array<keyboard.Shortcut>>;
