// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGroupedShortcuts() {
  return window['go']['keyboard']['KeyboardServiceInMemoryImpl']['GetGroupedShortcuts']();
}

export function GetShortcuts() {
  return window['go']['keyboard']['KeyboardServiceInMemoryImpl']['GetShortcuts']();
}
