// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ComponentFilter(arg1) {
  return window['go']['main']['App']['ComponentFilter'](arg1);
}

export function ComponentGet(arg1) {
  return window['go']['main']['App']['ComponentGet'](arg1);
}

export function FileGetLocalContent(arg1) {
  return window['go']['main']['App']['FileGetLocalContent'](arg1);
}

export function FileGetRemoteContent(arg1) {
  return window['go']['main']['App']['FileGetRemoteContent'](arg1);
}

export function GetFilesToBeCommited() {
  return window['go']['main']['App']['GetFilesToBeCommited']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Init() {
  return window['go']['main']['App']['Init']();
}

export function ResultGetAll(arg1) {
  return window['go']['main']['App']['ResultGetAll'](arg1);
}

export function SaveScanossBomFile() {
  return window['go']['main']['App']['SaveScanossBomFile']();
}
