// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {service} from '../models';

export function BeforeClose(arg1:context.Context):Promise<boolean>;

export function GetWorkingDir():Promise<string>;

export function Init(arg1:context.Context,arg2:service.ScanossSettingsService,arg3:service.KeyboardService):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetScanRoot(arg1:string):Promise<void>;
