// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileLocalFileContent(arg1) {
  return window['go']['main']['App']['FileLocalFileContent'](arg1);
}

export function FileRemoteFileContent(arg1) {
  return window['go']['main']['App']['FileRemoteFileContent'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
