// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	entities "github.com/scanoss/scanoss.lui/backend/main/pkg/component/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockComponentRepository is an autogenerated mock type for the ComponentRepository type
type MockComponentRepository struct {
	mock.Mock
}

type MockComponentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponentRepository) EXPECT() *MockComponentRepository_Expecter {
	return &MockComponentRepository_Expecter{mock: &_m.Mock}
}

// FindByFilePath provides a mock function with given fields: path
func (_m *MockComponentRepository) FindByFilePath(path string) (entities.Component, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for FindByFilePath")
	}

	var r0 entities.Component
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.Component, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) entities.Component); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(entities.Component)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComponentRepository_FindByFilePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByFilePath'
type MockComponentRepository_FindByFilePath_Call struct {
	*mock.Call
}

// FindByFilePath is a helper method to define mock.On call
//   - path string
func (_e *MockComponentRepository_Expecter) FindByFilePath(path interface{}) *MockComponentRepository_FindByFilePath_Call {
	return &MockComponentRepository_FindByFilePath_Call{Call: _e.mock.On("FindByFilePath", path)}
}

func (_c *MockComponentRepository_FindByFilePath_Call) Run(run func(path string)) *MockComponentRepository_FindByFilePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockComponentRepository_FindByFilePath_Call) Return(_a0 entities.Component, _a1 error) *MockComponentRepository_FindByFilePath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComponentRepository_FindByFilePath_Call) RunAndReturn(run func(string) (entities.Component, error)) *MockComponentRepository_FindByFilePath_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComponentRepository creates a new instance of MockComponentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponentRepository {
	mock := &MockComponentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
